/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Démonstration Hono + OpenAPI
 * Contrat HTTP généré depuis les routes Hono et leurs schémas Valibot.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export type GetApiUsers200Item = {
  id: string;
  name: string;
  email: string;
  createdAt: string;
};

export type PostApiUsersBody = {
  /** @minLength 1 */
  name: string;
  email: string;
};

export type PostApiUsers201 = {
  id: string;
  name: string;
  email: string;
  createdAt: string;
};

export type GetApiUsersById200 = {
  id: string;
  name: string;
  email: string;
  createdAt: string;
};

export type GetApiUsersById404 = {
  message: string;
};

export type GetApiUsersByIdPosts200Item = {
  id: string;
  userId: string;
  title: string;
  body: string;
  createdAt: string;
};

export type GetApiUsersByIdPosts404 = {
  message: string;
};

export type GetApiPostsById200 = {
  id: string;
  userId: string;
  title: string;
  body: string;
  createdAt: string;
};

export type GetApiPostsById404 = {
  message: string;
};

/**
 * @summary Lister les utilisateurs
 */
export type getApiUsersResponse200 = {
  data: GetApiUsers200Item[]
  status: 200
}

export type getApiUsersResponseSuccess = (getApiUsersResponse200) & {
  headers: Headers;
};
;

export type getApiUsersResponse = (getApiUsersResponseSuccess)

export const getGetApiUsersUrl = () => {


  

  return `/api/users`
}

export const getApiUsers = async ( options?: RequestInit): Promise<getApiUsersResponse> => {
  
  const res = await fetch(getGetApiUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiUsersResponse
}
  




export const getGetApiUsersQueryKey = () => {
    return [
    `/api/users`
    ] as const;
    }

    
export const getGetApiUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsers>>> = ({ signal }) => getApiUsers({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsers>>>
export type GetApiUsersQueryError = unknown


export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lister les utilisateurs
 */

export function useGetApiUsers<TData = Awaited<ReturnType<typeof getApiUsers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Créer un utilisateur
 */
export type postApiUsersResponse201 = {
  data: PostApiUsers201
  status: 201
}

export type postApiUsersResponse400 = {
  data: void
  status: 400
}

export type postApiUsersResponseSuccess = (postApiUsersResponse201) & {
  headers: Headers;
};
export type postApiUsersResponseError = (postApiUsersResponse400) & {
  headers: Headers;
};

export type postApiUsersResponse = (postApiUsersResponseSuccess | postApiUsersResponseError)

export const getPostApiUsersUrl = () => {


  

  return `/api/users`
}

export const postApiUsers = async (postApiUsersBody: PostApiUsersBody, options?: RequestInit): Promise<postApiUsersResponse> => {
  
  const res = await fetch(getPostApiUsersUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiUsersBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postApiUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postApiUsersResponse
}
  



export const getPostApiUsersMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsers>>, TError,{data: PostApiUsersBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postApiUsers>>, TError,{data: PostApiUsersBody}, TContext> => {

const mutationKey = ['postApiUsers'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiUsers>>, {data: PostApiUsersBody}> = (props) => {
          const {data} = props ?? {};

          return  postApiUsers(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiUsers>>>
    export type PostApiUsersMutationBody = PostApiUsersBody
    export type PostApiUsersMutationError = void

    /**
 * @summary Créer un utilisateur
 */
export const usePostApiUsers = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiUsers>>, TError,{data: PostApiUsersBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiUsers>>,
        TError,
        {data: PostApiUsersBody},
        TContext
      > => {
      return useMutation(getPostApiUsersMutationOptions(options), queryClient);
    }
    
/**
 * @summary Consulter un utilisateur
 */
export type getApiUsersByIdResponse200 = {
  data: GetApiUsersById200
  status: 200
}

export type getApiUsersByIdResponse404 = {
  data: GetApiUsersById404
  status: 404
}

export type getApiUsersByIdResponseSuccess = (getApiUsersByIdResponse200) & {
  headers: Headers;
};
export type getApiUsersByIdResponseError = (getApiUsersByIdResponse404) & {
  headers: Headers;
};

export type getApiUsersByIdResponse = (getApiUsersByIdResponseSuccess | getApiUsersByIdResponseError)

export const getGetApiUsersByIdUrl = (id: string,) => {


  

  return `/api/users/${id}`
}

export const getApiUsersById = async (id: string, options?: RequestInit): Promise<getApiUsersByIdResponse> => {
  
  const res = await fetch(getGetApiUsersByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiUsersByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiUsersByIdResponse
}
  




export const getGetApiUsersByIdQueryKey = (id: string,) => {
    return [
    `/api/users/${id}`
    ] as const;
    }

    
export const getGetApiUsersByIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsersById>>, TError = GetApiUsersById404>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersById>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersById>>> = ({ signal }) => getApiUsersById(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsersById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersById>>>
export type GetApiUsersByIdQueryError = GetApiUsersById404


export function useGetApiUsersById<TData = Awaited<ReturnType<typeof getApiUsersById>>, TError = GetApiUsersById404>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersById>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersById<TData = Awaited<ReturnType<typeof getApiUsersById>>, TError = GetApiUsersById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersById>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersById<TData = Awaited<ReturnType<typeof getApiUsersById>>, TError = GetApiUsersById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Consulter un utilisateur
 */

export function useGetApiUsersById<TData = Awaited<ReturnType<typeof getApiUsersById>>, TError = GetApiUsersById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Lister les publications d’un utilisateur
 */
export type getApiUsersByIdPostsResponse200 = {
  data: GetApiUsersByIdPosts200Item[]
  status: 200
}

export type getApiUsersByIdPostsResponse404 = {
  data: GetApiUsersByIdPosts404
  status: 404
}

export type getApiUsersByIdPostsResponseSuccess = (getApiUsersByIdPostsResponse200) & {
  headers: Headers;
};
export type getApiUsersByIdPostsResponseError = (getApiUsersByIdPostsResponse404) & {
  headers: Headers;
};

export type getApiUsersByIdPostsResponse = (getApiUsersByIdPostsResponseSuccess | getApiUsersByIdPostsResponseError)

export const getGetApiUsersByIdPostsUrl = (id: string,) => {


  

  return `/api/users/${id}/posts`
}

export const getApiUsersByIdPosts = async (id: string, options?: RequestInit): Promise<getApiUsersByIdPostsResponse> => {
  
  const res = await fetch(getGetApiUsersByIdPostsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiUsersByIdPostsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiUsersByIdPostsResponse
}
  




export const getGetApiUsersByIdPostsQueryKey = (id: string,) => {
    return [
    `/api/users/${id}/posts`
    ] as const;
    }

    
export const getGetApiUsersByIdPostsQueryOptions = <TData = Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError = GetApiUsersByIdPosts404>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiUsersByIdPostsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiUsersByIdPosts>>> = ({ signal }) => getApiUsersByIdPosts(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiUsersByIdPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiUsersByIdPosts>>>
export type GetApiUsersByIdPostsQueryError = GetApiUsersByIdPosts404


export function useGetApiUsersByIdPosts<TData = Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError = GetApiUsersByIdPosts404>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersByIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersByIdPosts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersByIdPosts<TData = Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError = GetApiUsersByIdPosts404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiUsersByIdPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiUsersByIdPosts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiUsersByIdPosts<TData = Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError = GetApiUsersByIdPosts404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lister les publications d’un utilisateur
 */

export function useGetApiUsersByIdPosts<TData = Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError = GetApiUsersByIdPosts404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiUsersByIdPosts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiUsersByIdPostsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary Consulter une publication
 */
export type getApiPostsByIdResponse200 = {
  data: GetApiPostsById200
  status: 200
}

export type getApiPostsByIdResponse404 = {
  data: GetApiPostsById404
  status: 404
}

export type getApiPostsByIdResponseSuccess = (getApiPostsByIdResponse200) & {
  headers: Headers;
};
export type getApiPostsByIdResponseError = (getApiPostsByIdResponse404) & {
  headers: Headers;
};

export type getApiPostsByIdResponse = (getApiPostsByIdResponseSuccess | getApiPostsByIdResponseError)

export const getGetApiPostsByIdUrl = (id: string,) => {


  

  return `/api/posts/${id}`
}

export const getApiPostsById = async (id: string, options?: RequestInit): Promise<getApiPostsByIdResponse> => {
  
  const res = await fetch(getGetApiPostsByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getApiPostsByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiPostsByIdResponse
}
  




export const getGetApiPostsByIdQueryKey = (id: string,) => {
    return [
    `/api/posts/${id}`
    ] as const;
    }

    
export const getGetApiPostsByIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPostsById>>, TError = GetApiPostsById404>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostsById>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPostsByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostsById>>> = ({ signal }) => getApiPostsById(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPostsById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPostsByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPostsById>>>
export type GetApiPostsByIdQueryError = GetApiPostsById404


export function useGetApiPostsById<TData = Awaited<ReturnType<typeof getApiPostsById>>, TError = GetApiPostsById404>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostsById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsById>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPostsById<TData = Awaited<ReturnType<typeof getApiPostsById>>, TError = GetApiPostsById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostsById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsById>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPostsById<TData = Awaited<ReturnType<typeof getApiPostsById>>, TError = GetApiPostsById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostsById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Consulter une publication
 */

export function useGetApiPostsById<TData = Awaited<ReturnType<typeof getApiPostsById>>, TError = GetApiPostsById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPostsById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPostsByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
